# wait
model: 'leyh'
#model_dir: 'data/model'
model_dir: 'data/model'
network: 'res'
heads: ''
task: 'pvnet'
gpus: (0, 1, 2, 3)
resume: true
#dataset_path: 'data/custom'
dataset_path: '/home/thws_robotik/Documents/Leyh/6dpose/datasets/HO3DBottle480p'
val_split: 0.8 #1 = all data to train dataset 
keypoint_cnt: 8 #number of keypoints

train:
    optim: 'adam'
    lr: 1e-3
    epoch: 500
    milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
    gamma: 0.9
    batch_size: 32
    dataset: 'LeyhTrain'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 1e-4 #0.
    batch_sampler: 'image_size'
    warmup: True
test:
    dataset: 'LeyhTest'
    batch_size: 1
    batch_sampler: 'image_size'
